import process from 'node:process';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs/promises';
import { expandTilde } from '../utils.js';
import type { ClaudexConfig } from '../config/schema.js';

export function getSshKeys(config: ClaudexConfig): string[] {
	if (!config.ssh?.keys) {
		return [];
	}

	return config.ssh.keys.map(key => expandTilde(key));
}

export function getSshHosts(config: ClaudexConfig): string[] {
	return config.ssh?.hosts ?? [];
}

export async function getFilteredKnownHosts(hosts: string[]): Promise<string> {
	if (hosts.length === 0) {
		return '';
	}

	const knownHostsPath = path.join(os.homedir(), '.ssh', 'known_hosts');

	try {
		const content = await fs.readFile(knownHostsPath, 'utf8');
		const lines = content.split('\n');
		const filtered: string[] = [];

		for (const line of lines) {
			const trimmed = line.trim();
			if (!trimmed || trimmed.startsWith('#')) {
				continue;
			}

			// Known_hosts format: hostname[,hostname...] keytype key [comment]
			const firstSpace = trimmed.indexOf(' ');
			if (firstSpace === -1) {
				continue;
			}

			const hostPart = trimmed.slice(0, Math.max(0, firstSpace));
			const hostnames = hostPart.split(',');

			// Check if any of the hostnames match our configured hosts
			for (const hostname of hostnames) {
				if (hosts.includes(hostname)) {
					filtered.push(line);
					break;
				}
			}
		}

		return filtered.join('\n') + (filtered.length > 0 ? '\n' : '');
	} catch {
		// Known_hosts doesn't exist or can't be read
		return '';
	}
}

export async function setupKnownHosts(): Promise<void> {
	const knownHostsContent = process.env.CLAUDEX_KNOWN_HOSTS_CONTENT;
	if (!knownHostsContent) {
		return;
	}

	const homeDir = os.homedir();
	const sshDir = path.join(homeDir, '.ssh');
	const knownHostsPath = path.join(sshDir, 'known_hosts');

	// Don't overwrite existing file
	try {
		await fs.access(knownHostsPath);
		console.log(`${knownHostsPath} already exists, skipping`);
		return;
	} catch {
		// File doesn't exist, create it
	}

	// Create .ssh directory with proper permissions
	await fs.mkdir(sshDir, { recursive: true, mode: 0o700 });

	// Write known_hosts file with proper permissions
	const contentWithHeader = `# Generated by claudex\n${knownHostsContent}`;
	await fs.writeFile(knownHostsPath, contentWithHeader, { mode: 0o600 });
	console.log(`Created ${knownHostsPath} with filtered known hosts`);
}
