import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import { paths } from './paths.js';
import { isErrnoException } from './utils.js';
import { allRules } from './hooks/rules/index.js';

const claudexMemoryDirectoryPath = path.join(paths.config, 'CLAUDE.md.d');

const defaultClaudeCodeMemoryPath = path.join(os.homedir(), '.claude', 'CLAUDE.md');

function prettifyPath(filePath: string) {
	const homeDir = os.homedir();

	if (filePath.startsWith(homeDir)) {
		filePath = filePath.replace(homeDir, '~');
	}

	return filePath;
}

const doNotEditThisFileMessage = [
	'Do not edit this file directly. It is automatically generated by claudex.',
	`Edit files in ${prettifyPath(claudexMemoryDirectoryPath)} instead.`,
].join('\n');

async function fileExists(filePath: string): Promise<boolean> {
	try {
		await fs.access(filePath);
		return true;
	} catch (error) {
		if (isErrnoException(error) && error.code === 'ENOENT') {
			return false;
		}

		throw error;
	}
}

async function getFilesInClaudexMemoryDirectory(): Promise<string[]> {
	const entriesInMemoryDirectory = await fs.readdir(claudexMemoryDirectoryPath, {
		withFileTypes: true,
	});

	const filesInMemoryDirectory = (
		entriesInMemoryDirectory
			.filter(entry => (
				(
					entry.isFile()
					|| entry.isSymbolicLink()
				)
				&& entry.name.endsWith('.md')
			))
			.sort((a, b) => a.name.localeCompare(b.name))
			.map(entry => path.join(entry.parentPath, entry.name))
	);

	return filesInMemoryDirectory;
}

async function shouldBackupClaudeCodeMemory(memoryPath: string): Promise<boolean> {
	try {
		const content = await fs.readFile(memoryPath, 'utf8');
		return !content.includes(doNotEditThisFileMessage);
	} catch (error) {
		if (isErrnoException(error) && error.code === 'ENOENT') {
			return false;
		}

		throw error;
	}
}

async function backupClaudeCodeMemory(memoryPath: string): Promise<void> {
	const backupPath = path.join(path.dirname(memoryPath), 'CLAUDE.md.bak');

	if (await fileExists(backupPath)) {
		const timestamp = new Date().toISOString().replaceAll(/[:.]/g, '-');
		const timestampedBackupPath = `${backupPath}.${timestamp}`;
		await fs.rename(memoryPath, timestampedBackupPath);
	} else {
		await fs.rename(memoryPath, backupPath);
	}
}

export async function createClaudeCodeMemory(resolvedHooks?: Record<string, boolean | undefined>, claudeConfigDir?: string) {
	const claudeCodeMemoryPath = claudeConfigDir
		? path.join(claudeConfigDir, 'CLAUDE.md')
		: defaultClaudeCodeMemoryPath;
	const filesInMemoryDirectory = await getFilesInClaudexMemoryDirectory();

	if (await shouldBackupClaudeCodeMemory(claudeCodeMemoryPath)) {
		console.warn('Backing up existing CLAUDE.md file...');
		await backupClaudeCodeMemory(claudeCodeMemoryPath);
	}

	await fs.writeFile(claudeCodeMemoryPath, (async function * () {
		yield doNotEditThisFileMessage;
		yield '\n\n';

		for (const file of filesInMemoryDirectory) {
			yield `# ${prettifyPath(file)}\n\n`;

			yield * fsSync.createReadStream(file, 'utf8');
			yield '\n\n';
		}

		if (resolvedHooks) {
			const enabledDescriptions = allRules
				.filter(r => resolvedHooks[r.meta.configKey])
				.map(r => `- ${r.meta.description}`);

			if (enabledDescriptions.length > 0) {
				yield '# Active Hook Rules\n\n';
				yield enabledDescriptions.join('\n');
				yield '\n\n';
			}
		}
	})());
}
